#!/bin/sh
#PBS -l select=1:ncpus=128:mpiprocs=128
#PBS -j oe
#PBS -N MC-T0-Nb
#PBS -l walltime=04:00:00
#PBS -q largemem
#PBS -l place=excl

module load parallel
source /home/app/anaconda3/bin/activate
conda init bash

conda activate casm

cd "$PBS_O_WORKDIR"

mkdir T_up_Nb_0
cd T_up_Nb_0
parallel -j 128 --delay 1 --joblog "joblog.txt" --verbose "../exe_T.sh {} {#} {%} null  10 1501 10" :::  `seq -1.000 0.005 0.001`   #${chem_pot} 
#At each chemical potential, scan the whole T range
