#!/bin/bash
GROUP=monte_carlo
export PATH=/userhome1/hengning/Fvib_CASMcode/CASMcode:$PATH
cd /userhome1/hengning/Fvib_CASMcode/CASMcode
mkdir -p /userhome1/hengning/Fvib_CASMcode/CASMcode/tests/unit/test_projects
: ${TEST_FLAGS:="--log_level=test_suite --catch_system_errors=no"}
/userhome1/hengning/Fvib_CASMcode/CASMcode/casm_unit_$GROUP ${TEST_FLAGS}
