#!/bin/bash
GROUP=crystallography
export PATH=/userhome1/hengning/CASMcode:$PATH
cd /userhome1/hengning/CASMcode
mkdir -p /userhome1/hengning/CASMcode/tests/unit/test_projects
: ${TEST_FLAGS:="--log_level=test_suite --catch_system_errors=no"}
/userhome1/hengning/CASMcode/casm_unit_$GROUP ${TEST_FLAGS}
