#!/bin/bash
GROUP=casm_io
export PATH=/app/CASMcode:$PATH
cd /app/CASMcode
mkdir -p /app/CASMcode/tests/unit/test_projects
: ${TEST_FLAGS:="--log_level=test_suite --catch_system_errors=no"}
/app/CASMcode/casm_unit_$GROUP ${TEST_FLAGS}
